package com.wavywalk.e164standarttringformatter.numberingplandata

class CountriesCountryCodesExitCodesAndTrunksData {

    companion object {
        //couldn't find it in normal format, so I had to scrape it from one site so it'd write in this file
        val data = arrayOf(
            arrayOf(
                    "Afghanistan",
                    "93",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Albania",
                    "355",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Algeria",
                    "213",
                    "00",
                    "0"
            ),
            arrayOf(
                    "American Samoa",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Andorra",
                    "376",
                    "00",
                    ""
            ),
            arrayOf(
                    "Angola",
                    "244",
                    "00",
                    ""
            ),
            arrayOf(
                    "Anguilla",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Antigua and Barbuda",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Argentina",
                    "54",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Armenia",
                    "374",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Aruba",
                    "297",
                    "00",
                    ""
            ),
            arrayOf(
                    "Ascension",
                    "247",
                    "00",
                    ""
            ),
            arrayOf(
                    "Australia",
                    "61",
                    "0011",
                    "0"
            ),
            arrayOf(
                    "Austria",
                    "43",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Azerbaijan",
                    "994",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Bahamas",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Bahrain",
                    "973",
                    "00",
                    ""
            ),
            arrayOf(
                    "Bangladesh",
                    "880",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Barbados",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Belarus",
                    "375",
                    "810",
                    "80"
            ),
            arrayOf(
                    "Belgium",
                    "32",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Belize",
                    "501",
                    "00",
                    ""
            ),
            arrayOf(
                    "Benin",
                    "229",
                    "00",
                    ""
            ),
            arrayOf(
                    "Bermuda",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Bhutan",
                    "975",
                    "00",
                    ""
            ),
            arrayOf(
                    "Bolivia",
                    "591",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Bosnia and Herzegovina",
                    "387",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Botswana",
                    "267",
                    "00",
                    ""
            ),
            arrayOf(
                    "Brazil",
                    "55",
                    "0014",
                    "0"
            ),
            arrayOf(
                    "Brazil (Telefonica)",
                    "55",
                    "0015",
                    "0"
            ),
            arrayOf(
                    "Brazil (Embratel)",
                    "55",
                    "0021",
                    "0"
            ),
            arrayOf(
                    "Brazil (Intelig)",
                    "55",
                    "0023",
                    "0"
            ),
            arrayOf(
                    "Brazil (Telmar)",
                    "55",
                    "0031",
                    "0"
            ),
            arrayOf(
                    "British Virgin Islands",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Brunei",
                    "673",
                    "00",
                    ""
            ),
            arrayOf(
                    "Bulgaria",
                    "359",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Burkina Faso",
                    "226",
                    "00",
                    ""
            ),
            arrayOf(
                    "Burundi",
                    "257",
                    "00",
                    ""
            ),
            arrayOf(
                    "Cambodia",
                    "855",
                    "001",
                    "0"
            ),
            arrayOf(
                    "Cambodia",
                    "855",
                    "008",
                    "0"
            ),
            arrayOf(
                    "Cambodia",
                    "855",
                    "007",
                    "0"
            ),
            arrayOf(
                    "Cameroon",
                    "237",
                    "00",
                    ""
            ),
            arrayOf(
                    "Canada",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Cape Verde",
                    "238",
                    "00",
                    ""
            ),
            arrayOf(
                    "Cayman Islands",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Central African Republic",
                    "236",
                    "00",
                    ""
            ),
            arrayOf(
                    "Chad",
                    "235",
                    "00",
                    ""
            ),
            arrayOf(
                    "Chile (Entel)",
                    "56",
                    "1230",
                    ""
            ),
            arrayOf(
                    "Chile  - Globus",
                    "56",
                    "1200",
                    ""
            ),
            arrayOf(
                    "Chile  - Manquehue",
                    "56",
                    "1220",
                    ""
            ),
            arrayOf(
                    "Chile Movistar",
                    "56",
                    "1810",
                    ""
            ),
            arrayOf(
                    "Chile  - Netline",
                    "56",
                    "1690",
                    ""
            ),
            arrayOf(
                    "Chile - Telmex",
                    "56",
                    "1710",
                    ""
            ),
            arrayOf(
                    "China",
                    "86",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Colombia UNE EPM",
                    "57",
                    "005",
                    "0"
            ),
            arrayOf(
                    "Colombia - ETB",
                    "57",
                    "007",
                    "0"
            ),
            arrayOf(
                    "Colombia  - Movistar",
                    "57",
                    "009",
                    "0"
            ),
            arrayOf(
                    "Colombia - Tigo",
                    "57",
                    "00414",
                    "0"
            ),
            arrayOf(
                    "Colombia  - Avantel",
                    "57",
                    "00468",
                    "0"
            ),
            arrayOf(
                    "Colombia  - Claro Fixed",
                    "57",
                    "00456",
                    "0"
            ),
            arrayOf(
                    "Colombia - Claro Mobile",
                    "57",
                    "00444",
                    "0"
            ),
            arrayOf(
                    "Comoros",
                    "269",
                    "00",
                    ""
            ),
            arrayOf(
                    "Congo",
                    "242",
                    "00",
                    ""
            ),
            arrayOf(
                    "Cook Islands",
                    "682",
                    "00",
                    ""
            ),
            arrayOf(
                    "Costa Rica",
                    "506",
                    "00",
                    ""
            ),
            arrayOf(
                    "Croatia",
                    "385",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Cuba",
                    "53",
                    "119",
                    "0"
            ),
            arrayOf(
                    "Curacao",
                    "599",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Cyprus",
                    "357",
                    "00",
                    ""
            ),
            arrayOf(
                    "Czech Republic",
                    "420",
                    "00",
                    ""
            ),
            arrayOf(
                    "Democratic Republic of Congo",
                    "243",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Denmark",
                    "45",
                    "00",
                    ""
            ),
            arrayOf(
                    "Diego Garcia",
                    "246",
                    "00",
                    ""
            ),
            arrayOf(
                    "Djibouti",
                    "253",
                    "00",
                    ""
            ),
            arrayOf(
                    "Dominica",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Dominican Republic",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "East Timor",
                    "670",
                    "00",
                    ""
            ),
            arrayOf(
                    "Ecuador",
                    "593",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Egypt",
                    "20",
                    "00",
                    "0"
            ),
            arrayOf(
                    "El Salvador",
                    "503",
                    "00",
                    ""
            ),
            arrayOf(
                    "Equatorial Guinea",
                    "240",
                    "00",
                    ""
            ),
            arrayOf(
                    "Eritrea",
                    "291",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Estonia",
                    "372",
                    "00",
                    ""
            ),
            arrayOf(
                    "Ethiopia",
                    "251",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Falkland (Malvinas) Islands",
                    "500",
                    "00",
                    ""
            ),
            arrayOf(
                    "Faroe Islands",
                    "298",
                    "00",
                    ""
            ),
            arrayOf(
                    "Fiji",
                    "679",
                    "00",
                    ""
            ),
            arrayOf(
                    "Finland",
                    "358",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Finland",
                    "358",
                    "990",
                    "0"
            ),
            arrayOf(
                    "Finland",
                    "358",
                    "994",
                    "0"
            ),
            arrayOf(
                    "Finland",
                    "358",
                    "999",
                    "0"
            ),
            arrayOf(
                    "France",
                    "33",
                    "00",
                    "0"
            ),
            arrayOf(
                    "French Guiana",
                    "594",
                    "00",
                    "0"
            ),
            arrayOf(
                    "French Polynesia",
                    "689",
                    "00",
                    ""
            ),
            arrayOf(
                    "Gabon",
                    "241",
                    "00",
                    ""
            ),
            arrayOf(
                    "Gambia",
                    "220",
                    "00",
                    ""
            ),
            arrayOf(
                    "Georgia",
                    "995",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Germany",
                    "49",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Ghana",
                    "233",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Gibraltar",
                    "350",
                    "00",
                    ""
            ),
            arrayOf(
                    "Greece",
                    "30",
                    "00",
                    ""
            ),
            arrayOf(
                    "Greenland",
                    "299",
                    "00",
                    ""
            ),
            arrayOf(
                    "Grenada",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Guadeloupe",
                    "590",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Guam",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Guatemala",
                    "502",
                    "00",
                    ""
            ),
            arrayOf(
                    "Guinea",
                    "224",
                    "00",
                    ""
            ),
            arrayOf(
                    "Guinea-Bissau",
                    "245",
                    "00",
                    ""
            ),
            arrayOf(
                    "Guyana",
                    "592",
                    "001",
                    ""
            ),
            arrayOf(
                    "Haiti",
                    "509",
                    "00",
                    ""
            ),
            arrayOf(
                    "Honduras",
                    "504",
                    "00",
                    ""
            ),
            arrayOf(
                    "Hong Kong",
                    "852",
                    "001",
                    ""
            ),
            arrayOf(
                    "Hungary",
                    "36",
                    "00",
                    "06"
            ),
            arrayOf(
                    "Iceland",
                    "354",
                    "00",
                    ""
            ),
            arrayOf(
                    "India",
                    "91",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Indonesia",
                    "62",
                    "001",
                    "0"
            ),
            arrayOf(
                    "Indonesia - Indosat",
                    "62",
                    "008",
                    "0"
            ),
            arrayOf(
                    "Indonesia  - Telkom",
                    "62",
                    "007",
                    "0"
            ),
            arrayOf(
                    "Indonesia - Bakrie Telecom",
                    "62",
                    "009",
                    "0"
            ),
            arrayOf(
                    "Inmarsat Satellite",
                    "870",
                    "00",
                    ""
            ),
            arrayOf(
                    "Iran",
                    "98",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Iraq",
                    "964",
                    "00",
                    ""
            ),
            arrayOf(
                    "Ireland",
                    "353",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Iridium Satellite",
                    "8817",
                    "00",
                    ""
            ),
            arrayOf(
                    "Iridium Satellite",
                    "8816",
                    "00",
                    ""
            ),
            arrayOf(
                    "Israel",
                    "972",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Israel",
                    "972",
                    "012",
                    "0"
            ),
            arrayOf(
                    "Israel",
                    "972",
                    "013",
                    "0"
            ),
            arrayOf(
                    "Israel",
                    "972",
                    "014",
                    "0"
            ),
            arrayOf(
                    "Israel",
                    "972",
                    "018",
                    "0"
            ),
            arrayOf(
                    "Italy",
                    "39",
                    "00",
                    ""
            ),
            arrayOf(
                    "Ivory Coast",
                    "225",
                    "00",
                    ""
            ),
            arrayOf(
                    "Jamaica",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Japan",
                    "81",
                    "010",
                    "0"
            ),
            arrayOf(
                    "Jordan",
                    "962",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Kazakhstan",
                    "7",
                    "810",
                    "8"
            ),
            arrayOf(
                    "Kenya",
                    "254",
                    "000",
                    "0"
            ),
            arrayOf(
                    "Kiribati",
                    "686",
                    "00",
                    ""
            ),
            arrayOf(
                    "Kuwait",
                    "965",
                    "00",
                    ""
            ),
            arrayOf(
                    "Kyrgyzstan",
                    "996",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Laos",
                    "856",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Latvia",
                    "371",
                    "00",
                    ""
            ),
            arrayOf(
                    "Lebanon",
                    "961",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Lesotho",
                    "266",
                    "00",
                    ""
            ),
            arrayOf(
                    "Liberia",
                    "231",
                    "00",
                    ""
            ),
            arrayOf(
                    "Libya",
                    "218",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Liechtenstein",
                    "423",
                    "00",
                    ""
            ),
            arrayOf(
                    "Lithuania",
                    "370",
                    "00",
                    "8"
            ),
            arrayOf(
                    "Luxembourg",
                    "352",
                    "00",
                    ""
            ),
            arrayOf(
                    "Macau",
                    "853",
                    "00",
                    ""
            ),
            arrayOf(
                    "Macedonia",
                    "389",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Madagascar",
                    "261",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Malawi",
                    "265",
                    "00",
                    ""
            ),
            arrayOf(
                    "Malaysia",
                    "60",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Maldives",
                    "960",
                    "00",
                    ""
            ),
            arrayOf(
                    "Mali",
                    "223",
                    "00",
                    ""
            ),
            arrayOf(
                    "Malta",
                    "356",
                    "00",
                    ""
            ),
            arrayOf(
                    "Marshall Islands",
                    "692",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Martinique",
                    "596",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Mauritania",
                    "222",
                    "00",
                    ""
            ),
            arrayOf(
                    "Mauritius",
                    "230",
                    "00",
                    ""
            ),
            arrayOf(
                    "Mayotte",
                    "262",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Mexico",
                    "52",
                    "00",
                    "01, 044, 045"
            ),
            arrayOf(
                    "Micronesia",
                    "691",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Moldova",
                    "373",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Monaco",
                    "377",
                    "00",
                    ""
            ),
            arrayOf(
                    "Mongolia",
                    "976",
                    "001",
                    "0"
            ),
            arrayOf(
                    "Montenegro",
                    "382",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Montserrat",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Morocco",
                    "212",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Mozambique",
                    "258",
                    "00",
                    ""
            ),
            arrayOf(
                    "Myanmar",
                    "95",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Namibia",
                    "264",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Nauru",
                    "674",
                    "00",
                    ""
            ),
            arrayOf(
                    "Nepal",
                    "977",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Netherlands",
                    "31",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Netherlands Antilles",
                    "599",
                    "00",
                    "0"
            ),
            arrayOf(
                    "New Caledonia",
                    "687",
                    "00",
                    ""
            ),
            arrayOf(
                    "New Zealand",
                    "64",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Nicaragua",
                    "505",
                    "00",
                    ""
            ),
            arrayOf(
                    "Niger",
                    "227",
                    "00",
                    ""
            ),
            arrayOf(
                    "Nigeria",
                    "234",
                    "009",
                    "0"
            ),
            arrayOf(
                    "Niue",
                    "683",
                    "00",
                    ""
            ),
            arrayOf(
                    "Norfolk Island",
                    "6723",
                    "00",
                    ""
            ),
            arrayOf(
                    "North Korea",
                    "850",
                    "99",
                    ""
            ),
            arrayOf(
                    "Northern Marianas",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Norway",
                    "47",
                    "00",
                    ""
            ),
            arrayOf(
                    "Oman",
                    "968",
                    "00",
                    ""
            ),
            arrayOf(
                    "Pakistan",
                    "92",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Palau",
                    "680",
                    "011",
                    ""
            ),
            arrayOf(
                    "Palestine",
                    "970",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Panama",
                    "507",
                    "00",
                    ""
            ),
            arrayOf(
                    "Papua New Guinea",
                    "675",
                    "00",
                    ""
            ),
            arrayOf(
                    "Paraguay",
                    "595",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Peru",
                    "51",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Philippines",
                    "63",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Poland",
                    "48",
                    "00",
                    ""
            ),
            arrayOf(
                    "Portugal",
                    "351",
                    "00",
                    ""
            ),
            arrayOf(
                    "Puerto Rico",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Qatar",
                    "974",
                    "00",
                    ""
            ),
            arrayOf(
                    "Reunion",
                    "262",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Romania",
                    "40",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Russian Federation",
                    "7",
                    "810",
                    "8"
            ),
            arrayOf(
                    "Rwanda",
                    "250",
                    "00",
                    ""
            ),
            arrayOf(
                    "Saint Helena",
                    "290",
                    "00",
                    ""
            ),
            arrayOf(
                    "Saint Kitts and Nevis",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Saint Lucia",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Saint Barthelemy",
                    "590",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Saint Martin (French part)",
                    "590",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Saint Pierre and Miquelon",
                    "508",
                    "00",
                    ""
            ),
            arrayOf(
                    "Saint Vincent and the Grenadines",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Samoa",
                    "685",
                    "0",
                    ""
            ),
            arrayOf(
                    "San Marino",
                    "378",
                    "00",
                    ""
            ),
            arrayOf(
                    "Sao Tome and Principe",
                    "239",
                    "00",
                    ""
            ),
            arrayOf(
                    "Saudi Arabia",
                    "966",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Senegal",
                    "221",
                    "00",
                    ""
            ),
            arrayOf(
                    "Serbia",
                    "381",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Seychelles",
                    "248",
                    "00",
                    ""
            ),
            arrayOf(
                    "Sierra Leone",
                    "232",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Singapore",
                    "65",
                    "001",
                    ""
            ),
            arrayOf(
                    "Singapore",
                    "65",
                    "008",
                    ""
            ),
            arrayOf(
                    "Sint Maarten",
                    "1",
                    "00",
                    "1"
            ),
            arrayOf(
                    "Slovakia",
                    "421",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Slovenia",
                    "386",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Solomon Islands",
                    "677",
                    "00",
                    ""
            ),
            arrayOf(
                    "Somalia",
                    "252",
                    "00",
                    ""
            ),
            arrayOf(
                    "South Africa",
                    "27",
                    "00",
                    "0"
            ),
            arrayOf(
                    "South Korea",
                    "82",
                    "001",
                    "0"
            ),
            arrayOf(
                    "South Korea",
                    "82",
                    "002",
                    "0"
            ),
            arrayOf(
                    "South Sudan",
                    "211",
                    "00",
                    ""
            ),
            arrayOf(
                    "Spain",
                    "34",
                    "00",
                    ""
            ),
            arrayOf(
                    "Sri Lanka",
                    "94",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Sudan",
                    "249",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Suriname",
                    "597",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Swaziland",
                    "268",
                    "00",
                    ""
            ),
            arrayOf(
                    "Sweden",
                    "46",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Switzerland",
                    "41",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Syria",
                    "963",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Taiwan",
                    "886",
                    "002",
                    "0"
            ),
            arrayOf(
                    "Tajikistan",
                    "992",
                    "810",
                    "8"
            ),
            arrayOf(
                    "Tanzania",
                    "255",
                    "000",
                    "0"
            ),
            arrayOf(
                    "Thailand",
                    "66",
                    "001",
                    "0"
            ),
            arrayOf(
                    "Thuraya Satellite",
                    "88216",
                    "00",
                    ""
            ),
            arrayOf(
                    "Togo",
                    "228",
                    "00",
                    ""
            ),
            arrayOf(
                    "Tokelau",
                    "690",
                    "00",
                    ""
            ),
            arrayOf(
                    "Tonga",
                    "676",
                    "00",
                    ""
            ),
            arrayOf(
                    "Trinidad and Tobago",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Tunisia",
                    "216",
                    "00",
                    ""
            ),
            arrayOf(
                    "Turkey",
                    "90",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Turkmenistan",
                    "993",
                    "810",
                    "8"
            ),
            arrayOf(
                    "Turks and Caicos Islands",
                    "1",
                    "0",
                    "1"
            ),
            arrayOf(
                    "Tuvalu",
                    "688",
                    "00",
                    ""
            ),
            arrayOf(
                    "Uganda",
                    "256",
                    "000",
                    "0"
            ),
            arrayOf(
                    "Ukraine",
                    "380",
                    "00",
                    "0"
            ),
            arrayOf(
                    "United Arab Emirates",
                    "971",
                    "00",
                    "0"
            ),
            arrayOf(
                    "United Kingdom",
                    "44",
                    "00",
                    "0"
            ),
            arrayOf(
                    "United States of America",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "U.S. Virgin Islands",
                    "1",
                    "011",
                    "1"
            ),
            arrayOf(
                    "Uruguay",
                    "598",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Uzbekistan",
                    "998",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Vanuatu",
                    "678",
                    "00",
                    ""
            ),
            arrayOf(
                    "Vatican City",
                    "379",
                    "00",
                    ""
            ),
            arrayOf(
                    "Vatican City",
                    "39",
                    "00",
                    ""
            ),
            arrayOf(
                    "Venezuela",
                    "58",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Vietnam",
                    "84",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Wallis and Futuna",
                    "681",
                    "00",
                    ""
            ),
            arrayOf(
                    "Yemen",
                    "967",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Zambia",
                    "260",
                    "00",
                    "0"
            ),
            arrayOf(
                    "Zimbabwe",
                    "263",
                    "00",
                    "0"
            )
            )

        }
}